// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add-item-to-cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('add-item-to-cart', async function() {
    await driver.get("https://www.shop-apotheke.com/")
    await driver.executeScript("window.scrollTo(0,408)")
    await driver.findElement(By.linkText("IBU-ratiopharm® 400 mg akut Schmerztabletten")).click()
    await driver.findElement(By.css(".tracking-\\[0\\.7px\\]")).click()
    await driver.findElement(By.id("GoToCart")).click()
    await driver.executeScript("window.scrollTo(0,791.3333129882812)")
    await driver.executeScript("window.scrollTo(0,1752)")
    await driver.executeScript("window.scrollTo(0,2322.666748046875)")
  })
})
